name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Runs on PRs against master.
  pull_request:
    branches:
      - master


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run:
          lake update
          lake build Aesop:shared Cli:shared ImportGraph:shared Mathlib:shared ProofWidgets:shared Qq:shared Batteries:shared LeanSearchClient:shared
          export LEAN_VERSION=`cat lean-toolchain` && export LEAN_VERSION=${LEAN_VERSION:17}
          mkdir -p .lake/build && g++ -shared -o .lake/build/libLean.so -Wl,--whole-archive -fvisibility=default $HOME/.elan/toolchains/leanprover--lean4---${LEAN_VERSION}/lib/lean/libLean.a -Wl,--no-whole-archive
          lake build
          export LIBRARY_PATH=$(pwd)/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$HOME/.elan/toolchains/leanprover--lean4---${LEAN_VERSION}/lib/lean/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/aesop/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/Cli/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/importGraph/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/mathlib/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/proofwidgets/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/Qq/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/batteries/.lake/build/lib/
          export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/.lake/packages/LeanSearchClient/.lake/build/lib/
          export LD_LIBRARY_PATH=$LIBRARY_PATH
          export CPLUS_INCLUDE_PATH=$HOME/.elan/toolchains/leanprover--lean4---${LEAN_VERSION}/include/
          g++ test.cpp -o test -lleanshared -lreverseffiwithmathlib
          ./test
